blank_issues_enabled: true
contact_links:
  - name: Support & Troubleshooting with the Zarathustra Community
    url:
    about: |
      For general questions and problems you are facing with Zarathustra, please search our community forums first.
