use clap::{App, Arg, SubCommand};

pub fn subcommand() -> App<'static, 'static> {
    SubCommand::with_name("deploy")
        .about("Deploy verifier contracts and manage on-chain verification")
        .subcommand(
            SubCommand::with_name("verifier")
                .about("Export and optionally deploy Solidity verifier contract")
                .arg(
                    Arg::with_name("input")
                        .help("Verification key file")
                        .required(true)
                        .index(1),
                )
                .arg(
                    Arg::with_name("output")
                        .long("output")
                        .short("o")
                        .help("Output Solidity file")
                        .default_value("verifier.sol"),
                )
                .arg(
                    Arg::with_name("rpc")
                        .long("rpc")
                        .help("RPC URL for deployment (optional, skips deploy if not set)"),
                )
                .arg(
                    Arg::with_name("private-key")
                        .long("private-key")
                        .help("Private key for deployment (use with --rpc)")
                        .required(false),
                ),
        )
        .subcommand(
            SubCommand::with_name("verify")
                .about("Submit a proof for on-chain verification")
                .arg(
                    Arg::with_name("proof")
                        .help("Proof JSON file")
                        .required(true)
                        .index(1),
                )
                .arg(
                    Arg::with_name("contract")
                        .help("Verifier contract address")
                        .required(true)
                        .index(2),
                )
                .arg(
                    Arg::with_name("rpc")
                        .long("rpc")
                        .help("RPC URL")
                        .required(true),
                ),
        )
        .subcommand(
            SubCommand::with_name("init")
                .about("Initialize a new project structure with deployment configs")
                .arg(
                    Arg::with_name("name")
                        .help("Project name")
                        .required(true)
                        .index(1),
                ),
        )
}

pub fn exec(matches: &clap::ArgMatches) -> Result<(), String> {
    match matches.subcommand() {
        ("verifier", Some(sub)) => exec_verifier(sub),
        ("verify", Some(sub)) => exec_verify(sub),
        ("init", Some(sub)) => exec_init(sub),
        _ => {
            subcommand().print_help().unwrap();
            println!();
            Ok(())
        }
    }
}

fn exec_verifier(matches: &clap::ArgMatches) -> Result<(), String> {
    let input = matches.value_of("input").unwrap();
    let output = matches.value_of("output").unwrap_or("verifier.sol");
    let rpc = matches.value_of("rpc");
    let pk = matches.value_of("private-key");

    if !std::path::Path::new(input).exists() {
        return Err(format!("Verification key not found: {}", input));
    }

    let vk_data =
        std::fs::read_to_string(input).map_err(|e| format!("Failed to read {}: {}", input, e))?;

    let preamble = format!(
        "// SPDX-License-Identifier: LGPL-3.0-only\n\
         pragma solidity ^0.8.0;\n\
         \n\
         // Generated by Zarathustra\n\
         // Verification key: {}\n\
         \n",
        input
    );

    let verifier_code = format!("{}{}", preamble, vk_data);
    std::fs::write(output, &verifier_code)
        .map_err(|e| format!("Failed to write {}: {}", output, e))?;

    println!("Verifier contract written to {}", output);

    if let (Some(rpc_url), Some(_pk)) = (rpc, pk) {
        println!("Deployment to {} not yet implemented (use cast or forge)", rpc_url);
        println!("Example: forge create {} --rpc-url {} --private-key <key>", output, rpc_url);
    }

    Ok(())
}

fn exec_verify(matches: &clap::ArgMatches) -> Result<(), String> {
    let proof = matches.value_of("proof").unwrap();
    let contract = matches.value_of("contract").unwrap();
    let rpc = matches.value_of("rpc").unwrap();

    println!("On-chain verification not yet implemented.");
    println!("Proof: {}", proof);
    println!("Contract: {}", contract);
    println!("RPC: {}", rpc);
    println!();
    println!("Use cast to verify:");
    println!(
        "  cast call {} \"verifyProof(...)\" --rpc-url {} <proof-params>",
        contract, rpc
    );
    Ok(())
}

fn exec_init(matches: &clap::ArgMatches) -> Result<(), String> {
    let name = matches.value_of("name").unwrap();
    let base = std::path::Path::new(name);

    if base.exists() {
        return Err(format!("Directory '{}' already exists", name));
    }

    std::fs::create_dir_all(base.join("circuits"))
        .map_err(|e| format!("Failed to create directory: {}", e))?;
    std::fs::create_dir_all(base.join("contracts"))
        .map_err(|e| format!("Failed to create directory: {}", e))?;
    std::fs::create_dir_all(base.join("scripts"))
        .map_err(|e| format!("Failed to create directory: {}", e))?;
    std::fs::create_dir_all(base.join("proofs"))
        .map_err(|e| format!("Failed to create directory: {}", e))?;

    let readme = format!(
        "# {}\n\n\
         Zarathustra zkSNARK project\n\n\
         ## Structure\n\n\
         - `circuits/` - Circuit source files (.zara)\n\
         - `contracts/` - Solidity verifier contracts\n\
         - `scripts/` - Build and deployment scripts\n\
         - `proofs/` - Generated proofs\n\n\
         ## Quick Start\n\n\
         ```bash\n\
         zarathustra prove compile -i circuits/main.zara\n\
         zarathustra prove setup\n\
         zarathustra prove compute-witness -a <inputs>\n\
         zarathustra prove generate-proof\n\
         zarathustra prove verify\n\
         ```\n",
        name
    );
    std::fs::write(base.join("README.md"), &readme)
        .map_err(|e| format!("Failed to write README: {}", e))?;

    let main_circuit = "def main(field a, field b) -> field {\n    assert(a * a == b);\n    return a;\n}\n";
    std::fs::write(base.join("circuits").join("main.zara"), main_circuit)
        .map_err(|e| format!("Failed to write circuit: {}", e))?;

    println!("Initialized project: {}", name);
    println!("  circuits/main.zara - example circuit");
    println!("  contracts/         - verifier contracts");
    println!("  scripts/           - deployment scripts");
    println!("  proofs/            - proof outputs");

    Ok(())
}
